# Generated by Django 6.0.3 on 2026-03-06 11:29

from django.db import migrations

import apps.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
    ]
