# Generated by Django 6.0.3 on 2026-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_fix_slug_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("subscription", "По подписке"),
                    ("one_time", "Разовый платёж"),
                ],
                default="subscription",
                max_length=20,
                verbose_name="Тип доступа",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Цена в USD для отдельных платных постов",
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
