# Generated by Django 6.0.3 on 2026-03-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_post_payment_type_alter_post_price"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="content_pos_created_415459_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="content_pos_status_90c640_idx",
        ),
        migrations.AlterField(
            model_name="post",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Только по подписке"),
        ),
        migrations.RemoveField(
            model_name="post",
            name="payment_type",
        ),
        migrations.RemoveField(
            model_name="post",
            name="price",
        ),
    ]
